insert into  team values(1,'Angola','D');
insert into  team values(10,'France','G');
insert into  team values(11,'Germany','A');
insert into  team values(12,'Ghana','E');
insert into  team values(13,'Iran','D');
insert into  team values(14,'Italy','E');
insert into  team values(15,'Ivory Coast','C');
insert into  team values(16,'Japan','F');
insert into  team values(17,'Mexico','D');
insert into  team values(18,'Netherlands','C');
insert into  team values(19,'Paraguay','B');
insert into  team values(2,'Argentina','C');
insert into  team values(20,'Poland','A');
insert into  team values(21,'Portugal','D');
insert into  team values(22,'Saudi Arabia','H');
insert into  team values(23,'Serbia + Montenegro','C');
insert into  team values(24,'South Korea','G');
insert into  team values(25,'Spain','H');
insert into  team values(26,'Sweden','B');
insert into  team values(27,'Switzerland','G');
insert into  team values(28,'Togo','G');
insert into  team values(29,'Trinidad + Tobago','B');
insert into  team values(3,'Australia','F');
insert into  team values(30,'Tunisia','H');
insert into  team values(31,'Ukraine','F');
insert into  team values(32,'United States','E');
insert into  team values(4,'Brazil','F');
insert into  team values(5,'Costa Rica','A');
insert into  team values(6,'Croatia','F');
insert into  team values(7,'Czech Republic','E');
insert into  team values(8,'Ecuador','A');
insert into  team values(9,'England','B');

