

create table team (
	TNO		NUMERIC (2,0) CONSTRAINT PK_TEAM PRIMARY KEY,
	TNA		CHAR (20),
	GRP	 	CHAR (1) 
);

create table game (
	GNO		NUMERIC CONSTRAINT PK_GAME PRIMARY KEY,
	GAME_DATE	DATE,
	TEAM_1		NUMERIC (2,0) CONSTRAINT REF_GAME_1 REFERENCES TEAM(TNO),
	TEAM_1_GOALS	NUMERIC (2,0),
	TEAM_2		NUMERIC (2,0) CONSTRAINT REF_GAME_2 REFERENCES TEAM(TNO),
	TEAM_2_GOALS	NUMERIC (2,0),
	ROUND		CHAR (7) 
);

